apache/incubator-nuttx-testing

cibuild.sh

Apache jenkins slave may not have gperf installed, so make gperf prebuilt
which needed in kconfig-frontends configure.

Add prebuilt gperf needed in kconfig-frontends configure

---

cibuild.sh

1. In nuttx and apps PR check build, github action/jenkins/travis CI would
checkout repos accordingly. So decouple -b option to do run_builds only.
2. And if do builds starting from testing repo, call cibuild.sh as below:
./cibuild.sh -i -s -b check or ./cibuild.sh -i -s -b full
Change-Id: I5cd0b87aed37ddab117d17aa5b72744c2db2aac6

cibuild.sh: decouple -b option to do run_builds only

---

cibuild.sh

Since -si/sl options have been removed from testbuild.sh, so remove
it here.

cibuild.sh: remove -si option since testbuild.sh updated

---

testlist/fulllist.dat

Remove sim:mtdpart and sim:mtdrwb configs since i386 libz not available
now in Apache Jenkins slaves. Revert this change once i386 libz installed.
Build error logs:
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libz.so when searching for -lz
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libz.a when searching for -lz
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status

fulllist: remove sim:mtdpart and sim:mtdrwb configs

---

testlist/fulllist.dat

since INFRA fix this issue:
https://github.com/apache/infrastructure-p6/pull/258

Revert "fulllist: remove sim:mtdpart and sim:mtdrwb configs"

---

cibuild.sh
testlist/full.dat

1. Add xtensa esp32 gcc toolchain
2. Add xtensa esp32 boards into full testlist fistly
Note nuttx and apps github action workflows also need update accordingly if esp32 boards into check build testlist:
1. docker image updated with xtensa toolchain firstly
2. use 'mips-riscv-x86-xtensa'  instead of 'mips-riscv-x86' in matrix boards

Add xtensa esp32 boards build support

---

.github/workflows/docker_linux.yml
docker/linux/Dockerfile

This is a reworking of the Docker container to be used with the GitHub Action CI job for github.com/apache/incubator-nuttx
This should likely replace the PR #13 producing a more modular and smaller docker image.  This will also build the docker image on a PR, but will also publish it to this project only on merge.

Add Dockerfile for CI system and hook into GitHub Actions

---

docker/linux/Dockerfile
testlist/mips-riscv-x86-xtensa.dat

The bootloader and partition-table blobs are now built as part of the CI image and placed here `/tools/blobs/esp32core/`  The thought is any other binary blobs that we might need for other testing can also be placed here, for example the Broadcom WIFI firmware.
There is an example CI run using this here showing everything passing include the xtensa builds: https://github.com/btashton/incubator-nuttx/runs/526365535?check_suite_focus=true

Docker: Build the needed binaries from esp-idf

---

cibuild.sh

This configures a the python user installation environment and then installs the `esptool` dependency.  Should resolve the nightly build issue and enable us to more easily install python dependencies in the ci scripts.

Configure python environment and install esptool

---

cibuild.sh

So suppress the nightly and check build warnings with pre-processor directive #warning in GCC.

cibuild.sh: call testbuild.sh with '-e -Wno-cpp' option defaultly

---

.github/workflows/build.yml

From:
PR Check CI (build) / build-linux (arm-02) (pull_request)
To:
Build / Linux (arm-02) (pull_request)

CI: Make job descriptions less redundant

---

cibuild.sh

This PR depends on https://github.com/apache/incubator-nuttx/pull/792 merged in, and then all the existing warnings fixed. So defer to merge it now.

cibuild.sh: enable -Werror for precheck and nightly build defaultly

---

.github/actions/ci-container/action.yaml

The github action that we had defined for running builds in the container did not have the input `run` defined, so there were warning annotations on every build.
Removes warning from all the Linux builds
The warning annotation should not exist anymore in the CI check.

Fix the warning of undefined input we were using on the build action

---

.github/workflows/build.yml
cibuild.sh
docker/linux/Dockerfile
testlist/avr-mips-riscv-x86-xtensa.dat

Adds AVR GCC compiler to Darwin environment and to Linux Docker container. 
Adds AVR configurations to CI targets
Note we are not using the Microchip toolchain because it is behind a login wall.  The Homebrew tap and the Ubuntu version are both quite stable and up-to-date
This is also bumping the base Ubuntu version from 19.04 -> 19.10 as 19.04 is EOL.

Add support for building avr targets

---

testlist/avr-mips-riscv-x86-xtensa.dat

This removes the avr targets from the ci build until we can address the warnings in the OS for the architecture.  This should be reverted later, but unblocks other builds.

Disable AVR until we get some warnings resolved

---

testlist/avr-mips-riscv-x86-xtensa.dat

Reverts apache/incubator-nuttx-testing#51

Re-Enable AVR now that master builds AVR correctly

---

.github/actions/ci-container/action.yaml
docker/linux/Dockerfile

Two small changes that I found useful having while setting up a Dockerized environment for testing NuttX on the ESP32 platform.
Should cause none.
Ran a dockerized build of the esp32-core:nsh configuration and flashed it onto my DevKitC module, worked ok.

Additions for ESP32

---

cibuild.sh
docker/linux/Dockerfile

Add https://github.com/google/bloaty to the CI tool builds so we can start integrating it into the build flow.
This does not yet change the CI flow to use the utility yet.
Was able to run bloaty from the docker image that is created.

CI: Add bloaty utility to the ci tools

---

testlist/sim.dat

Disable sim sotest32 config build since it doesn't work on macOS, just like module32 config.

sim.dat: disable sim:sotest32 config since not work under macOS

---

.github/workflows/build.yml
cibuild.sh
docker/linux/Dockerfile

Some of our builds especially on MacOS are still fairly slow.  This fix enabled ccache for both Linux and MacOS builds with cross build cache maintained via GitHub Actions cache.
The improvement on MacOS is less but on some Linux builds times are nearly cut in half.

CI: Enable ccache for builds

---

docker/linux/Dockerfile

Switch to Ubuntu LTS 20.10 relaese for base image
Moving to the latest LTS release from a 19.10 non LTS release.

Switch to Ubuntu LTS 20.04 relaese for base image

---

.github/actions/ci-container/action.yaml

This fixes one of the issues I found with CI. The call on NuttX workflow is like:
<pre>
testbuild.sh
ccache -s
</pre>
and even if `testbuild.sh` failed, since `ccache` didn't, this did not fail the test. 
Fixes CI
Not possible, will have to do once merged.

make bash abort on error

---

cibuild.sh

cibuild.sh: add objcopy support to MacOS
cibuild.sh: add objcopy support to MacOS

cibuild.sh: add objcopy support to MacOS

---

cibuild.sh

cibuild.sh: fix binutils path error

cibuild.sh: fix binutils path error

---

cibuild.sh

follow up the apps repo change:
```
commit 18137c0fec3cea30871f29238e11ea0f4e8523da
Author: Matias N <matias@protobits.dev>
Date:   Sat Sep 12 00:36:23 2020 -0300
Fix: ensure archive files do not carry object files from prior builds
This is the corresponding change to the one on main NuttX repo. In this
case this involves splitting the build of libapps.a into: a) building
all applications (which is safely parallelizable), b) adding each
application's object files to the archive in turns (serial by nature).
This removes the need for the flock used to protect the parallel build.
Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>
```

cibuild.sh: Remove the flock installation

---

cibuild.sh

We create a simlink in prebuilt for certain tools like objcopy that are brew installed from binutils.  It is likely that we will cache the simlink, but still need to brew install binutils this will fail because we will try to create the symlink again. This change always recreates the symlink if the brew install was required.
MacOS CI builds should be more reliable.
CI Builds

ci: Handle case where prebuilt was cached but brew install binutils

---

.github/workflows/build.yml
cibuild.sh
testlist/all.dat
testlist/renesas.dat

Added renesas pre-check for RX65N
cibuild.sh: Textinfo issue for RX toolchain compilation resolved
To enable the renesas pre-check
Tested RX toolchain compilation

Added renesas precheck

---

testlist/sim.dat

To fix the issue: https://github.com/apache/incubator-nuttx/issues/2094
Need merge https://github.com/apache/incubator-nuttx/pull/2128 first.
The automation build

testlist/sim.dat: Skip 32bit sim build only for macOS

---

.github/workflows/build.yml
testlist/other.dat

will remove avr-mips-riscv-x86-xtensa.dat and renesas.dat after the script in nuttx/apps update

testlist: Merge avr-mips-riscv-x86-xtensa.dat and renesas.dat into other.dat

---

testlist/sim.dat

LVGL uses X11 which is not available on macOS
CI
CI

add sim:lvgl to macOS exceptions

---

docker/linux/Dockerfile
testlist/sim.dat

This adds the required libraries to the Linux CI docker image to support building a config that requires libalsa2 for audio testing
There is also a currently non existing config for ALSA that is blocked from building on macOS.
This supports this PR https://github.com/apache/incubator-nuttx/pull/2124 and should be merged ahead of time to support better testing.
CI

Add ALSA support in CI

---

docker/linux/Dockerfile
testlist/sim.dat

Add Linux headers to docker image.  This supports simulator targets that are Linux specific such as https://github.com/apache/incubator-nuttx/pull/2158
This also adds a block entry in the testlists for macOS for any sim config that starts with sim:linux this way we don't have to keep adding entries all the time if they are Linux specific.

CI: Add Linux headers to docker image

---

docker/linux/Dockerfile

add gawk to docker, used for build ltp on nuttx
no
test on local

docker: add gawk to docker

---

.github/workflows/build.yml
.github/workflows/docker_linux.yml
.github/workflows/lint.yml

See https://github.com/apache/incubator-nuttx/pull/2622
*In addition to the problem listed here this also brings this in-line with the OS workflow files and adds some more linting*
Apache Infrastructure recently made a change to the GitHub projects so that they cannot use actions that are not under the Apache org, GitHub org, or verified.   We were using some outside of this and this prevented builds from running.
Policy:
* https://infra.apache.org/github-actions-secrets.html
Discussion builds@apache.org:
* https://lists.apache.org/thread.html/r435c45dfc28ec74e28314aa9db8a216a2b45ff7f27b15932035d3f65%40%3Cbuilds.apache.org%3E
Discussion users@infra.apache.org:
* https://lists.apache.org/thread.html/r900f8f9a874006ed8121bdc901a0d1acccbb340882c1f94dad61a5e9%40%3Cusers.infra.apache.org%3E …

CI: Only use approved GitHub Actions

---

docker/linux/Dockerfile

Install libpython2.7 for xtensa-esp32-elf-gdb
root@5b2362eb60c2:/src/nuttx# ldd /tools/xtensa-esp32-elf-gcc/bin/xtensa-esp32-elf-gdb
linux-vdso.so.1 (0x00007ffeb59f3000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2a7fc31000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2a7fc0e000)
libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f2a7fc09000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2a7faba000)
libpython2.7.so.1.0 => /lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f2a7f74e000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2a7f55c000)
/lib64/ld-linux-x86-64.so.2 (0x00007f2a7fc3f000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2a7f53e000)
root@5b2362eb60c2:/src/nuttx#
increase the image size a bit

nuttx-ci-linux: Install libpython2.7 for xtensa-esp32-elf-gdb

---

testlist/other.dat

Homebrew issue with AVR toolchain here is preventing avg-gcc from installing on the macOS runners.
https://github.com/osx-cross/homebrew-avr/issues/205
AVR builds will be disabled on macOS until the upstream toolchain issue is resolved
CI

Disable AVR targets on macOS due to homebrew issue

---

docker/linux/Dockerfile

Workaround the following failure I have with "docker build" on
Docker Desktop on macOS.
It might be related to https://github.com/docker/for-linux/issues/1131.
E: Could not configure 'libc6:i386'.
E: Could not perform immediate configuration on 'libgcc-s1:i386'. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)
The command '/bin/sh -c apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -y -qq --no-install-recommends   avr-libc   build-essential   ccache   curl   gcc   gcc-avr   gcc-multilib   gettext   git   lib32z1-dev   libc6-dev-i386   libasound2-dev libasound2-dev:i386   libcurl4-openssl-dev   libpulse-dev libpulse-dev:i386   libpython2.7   libx11-dev libx11-dev:i386   libxext-dev libxext-dev:i386   linux-libc-dev:i386   linux-headers-generic …

Dockerfile: APT::Immediate-Configure=0 to workaround failures

---

docker/linux/Dockerfile

https://github.com/apache/incubator-nuttx-testing/pull/83 was applied to the wrong instance of apt-get.
this PR fixes it.
built and tested locally (with https://github.com/apache/incubator-nuttx-testing/pull/86)

Reapply xtensa gdb fix to the right section

---

cibuild.sh
testlist/other.dat

Reverts apache/incubator-nuttx-testing#85

Revert "Disable AVR targets on macOS due to homebrew issue"

---

docker/linux/Dockerfile

Don't clone and build an IDF example to get the ESP32 binaries.  Rather, use the esp-nuttx-bootloader repo.

docker/linux/Dockerfile: Don't use IDF to get the ESP32 binaries.

---

testlist/other.dat

since macOS build never reference other.dat

other.dat: Remove the Darwin black list
